version: "3.3"

services: 
  api:
    build: 
      context: .
      dockerfile: Dockerfile
    labels: 
      - "traefik.enable=true"
      - "traefik.http.routers.api-rtr.rule=Host(`cobb.localhost`)"
      - "traefik.http.services.api-svs.loadbalancer.server.port=3000"
    depends_on: 
      - mongodb
    networks: 
      - internal
    volumes: 
      - app_volume:/usr/src/app

  traefik:
    image: traefik:v2.1
    command:
      - --api.insecure=true # Don't do that in production!
      - --log=true
      - --accessLog=true
      - --accessLog.filePath=/traefik.log
      - --accessLog.bufferingSize=100
      - --accessLog.filters.statusCodes=400-499
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --providers.docker.network=internal
    ports:
      - 3000:80
      - 3001:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - internal
      - default

  mongodb:
    image: mongo:4.2
    container_name: mongodb
    environment: 
      - MONGO_INITDB_DATABASE=${DB_NAME}
      - MONGO_INITDB_ROOT_USERNAME=${DB_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_PASSWORD}
    volumes: 
      - mongodbdata:/data/db
    networks: 
      - internal

networks:
  internal:

volumes: 
  mongodbdata:
  app_volume:
    driver: local
    driver_opts: 
      type: nfs
      device: ${APP_DIR}
      o: bind
  # mongodb:
  #   driver: local
  #   driver_opts: 
  #     type: nfs
  #     device: ${MONGO_DIR}
  #     o: bind
